
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Activity : Luban.BeanBase
{
    public Activity(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = _buf["type"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["banner"].IsString) { throw new SerializationException(); }  Banner = _buf["banner"]; }
        { if(!_buf["bannerTittle"].IsString) { throw new SerializationException(); }  BannerTittle = _buf["bannerTittle"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["showUiType"].IsString) { throw new SerializationException(); }  ShowUiType = _buf["showUiType"]; }
        { if(!_buf["priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["priority"]; }
        { if(!_buf["onoff"].IsNumber) { throw new SerializationException(); }  Onoff = _buf["onoff"]; }
        { if(!_buf["condition"].IsString) { throw new SerializationException(); }  Condition = _buf["condition"]; }
        { if(!_buf["show_condition"].IsString) { throw new SerializationException(); }  ShowCondition = _buf["show_condition"]; }
        { if(!_buf["server_open_day"].IsString) { throw new SerializationException(); }  ServerOpenDay = _buf["server_open_day"]; }
        { if(!_buf["limit_day"].IsNumber) { throw new SerializationException(); }  LimitDay = _buf["limit_day"]; }
        { if(!_buf["timeType"].IsNumber) { throw new SerializationException(); }  TimeType = _buf["timeType"]; }
        { if(!_buf["para1"].IsString) { throw new SerializationException(); }  Para1 = _buf["para1"]; }
        { if(!_buf["para2"].IsString) { throw new SerializationException(); }  Para2 = _buf["para2"]; }
        { if(!_buf["para3"].IsString) { throw new SerializationException(); }  Para3 = _buf["para3"]; }
        { if(!_buf["para4"].IsString) { throw new SerializationException(); }  Para4 = _buf["para4"]; }
        { if(!_buf["limitTime"].IsNumber) { throw new SerializationException(); }  LimitTime = _buf["limitTime"]; }
        { if(!_buf["test_para1"].IsString) { throw new SerializationException(); }  TestPara1 = _buf["test_para1"]; }
        { if(!_buf["test_para2"].IsString) { throw new SerializationException(); }  TestPara2 = _buf["test_para2"]; }
        { if(!_buf["test_para3"].IsString) { throw new SerializationException(); }  TestPara3 = _buf["test_para3"]; }
        { if(!_buf["test_para4"].IsString) { throw new SerializationException(); }  TestPara4 = _buf["test_para4"]; }
        { if(!_buf["test_limitTime"].IsNumber) { throw new SerializationException(); }  TestLimitTime = _buf["test_limitTime"]; }
        { if(!_buf["tableInfo"].IsString) { throw new SerializationException(); }  TableInfo = _buf["tableInfo"]; }
        { if(!_buf["tableInfoType"].IsNumber) { throw new SerializationException(); }  TableInfoType = _buf["tableInfoType"]; }
        { if(!_buf["rankType"].IsString) { throw new SerializationException(); }  RankType = _buf["rankType"]; }
        { if(!_buf["mailId"].IsNumber) { throw new SerializationException(); }  MailId = _buf["mailId"]; }
        { if(!_buf["serverId"].IsString) { throw new SerializationException(); }  ServerId = _buf["serverId"]; }
        { if(!_buf["festivalEntrance"].IsNumber) { throw new SerializationException(); }  FestivalEntrance = _buf["festivalEntrance"]; }
        { if(!_buf["extra_display_hour"].IsNumber) { throw new SerializationException(); }  ExtraDisplayHour = _buf["extra_display_hour"]; }
        { if(!_buf["delete_activity_item"].IsString) { throw new SerializationException(); }  DeleteActivityItem = _buf["delete_activity_item"]; }
        { if(!_buf["open_country"].IsString) { throw new SerializationException(); }  OpenCountry = _buf["open_country"]; }
        { if(!_buf["close_country"].IsString) { throw new SerializationException(); }  CloseCountry = _buf["close_country"]; }
    }

    public static Activity DeserializeActivity(JSONNode _buf)
    {
        return new Activity(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 活动名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 活动图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 宣传图
    /// </summary>
    public readonly string Banner;
    /// <summary>
    /// 宣传图标题
    /// </summary>
    public readonly string BannerTittle;
    /// <summary>
    /// 活动说明
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// UI类型
    /// </summary>
    public readonly string ShowUiType;
    /// <summary>
    /// 显示优先级
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 开关
    /// </summary>
    public readonly int Onoff;
    /// <summary>
    /// 活动开启条件
    /// </summary>
    public readonly string Condition;
    /// <summary>
    /// 活动显示条件
    /// </summary>
    public readonly string ShowCondition;
    /// <summary>
    /// 服务器开始天数
    /// </summary>
    public readonly string ServerOpenDay;
    /// <summary>
    /// 活动剩余时间少于x天就不开
    /// </summary>
    public readonly int LimitDay;
    /// <summary>
    /// 时间类型
    /// </summary>
    public readonly int TimeType;
    /// <summary>
    /// 参数1
    /// </summary>
    public readonly string Para1;
    /// <summary>
    /// 参数2
    /// </summary>
    public readonly string Para2;
    /// <summary>
    /// 参数3
    /// </summary>
    public readonly string Para3;
    /// <summary>
    /// 参数4
    /// </summary>
    public readonly string Para4;
    /// <summary>
    /// 持续时间
    /// </summary>
    public readonly int LimitTime;
    /// <summary>
    /// 测试服参数1
    /// </summary>
    public readonly string TestPara1;
    /// <summary>
    /// 测试服参数2
    /// </summary>
    public readonly string TestPara2;
    /// <summary>
    /// 测试服参数3
    /// </summary>
    public readonly string TestPara3;
    /// <summary>
    /// 测试服参数4
    /// </summary>
    public readonly string TestPara4;
    /// <summary>
    /// 测试服持续时间
    /// </summary>
    public readonly int TestLimitTime;
    /// <summary>
    /// 关联活动表
    /// </summary>
    public readonly string TableInfo;
    /// <summary>
    /// 活动表中的类型
    /// </summary>
    public readonly int TableInfoType;
    /// <summary>
    /// 排行榜类型
    /// </summary>
    public readonly string RankType;
    /// <summary>
    /// 奖励邮件ID
    /// </summary>
    public readonly int MailId;
    /// <summary>
    /// 服务器ID
    /// </summary>
    public readonly string ServerId;
    /// <summary>
    /// 入口类型
    /// </summary>
    public readonly int FestivalEntrance;
    /// <summary>
    /// 活动结束后额外显示时间（小时）
    /// </summary>
    public readonly int ExtraDisplayHour;
    /// <summary>
    /// 活动结束后删除道具
    /// </summary>
    public readonly string DeleteActivityItem;
    /// <summary>
    /// 开启的国家
    /// </summary>
    public readonly string OpenCountry;
    /// <summary>
    /// 不开的国家
    /// </summary>
    public readonly string CloseCountry;
   
    public const int __ID__ = -1591322833;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "icon:" + Icon + ","
        + "banner:" + Banner + ","
        + "bannerTittle:" + BannerTittle + ","
        + "desc:" + Desc + ","
        + "showUiType:" + ShowUiType + ","
        + "priority:" + Priority + ","
        + "onoff:" + Onoff + ","
        + "condition:" + Condition + ","
        + "showCondition:" + ShowCondition + ","
        + "serverOpenDay:" + ServerOpenDay + ","
        + "limitDay:" + LimitDay + ","
        + "timeType:" + TimeType + ","
        + "para1:" + Para1 + ","
        + "para2:" + Para2 + ","
        + "para3:" + Para3 + ","
        + "para4:" + Para4 + ","
        + "limitTime:" + LimitTime + ","
        + "testPara1:" + TestPara1 + ","
        + "testPara2:" + TestPara2 + ","
        + "testPara3:" + TestPara3 + ","
        + "testPara4:" + TestPara4 + ","
        + "testLimitTime:" + TestLimitTime + ","
        + "tableInfo:" + TableInfo + ","
        + "tableInfoType:" + TableInfoType + ","
        + "rankType:" + RankType + ","
        + "mailId:" + MailId + ","
        + "serverId:" + ServerId + ","
        + "festivalEntrance:" + FestivalEntrance + ","
        + "extraDisplayHour:" + ExtraDisplayHour + ","
        + "deleteActivityItem:" + DeleteActivityItem + ","
        + "openCountry:" + OpenCountry + ","
        + "closeCountry:" + CloseCountry + ","
        + "}";
    }
}

}

