
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbItem TbItem {get; }
    public TbActivity TbActivity {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbItem = new TbItem(loader("tbitem"));
        TbActivity = new TbActivity(loader("tbactivity"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbActivity.ResolveRef(this);
    }
}

}
