
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbActivity
{
    private readonly System.Collections.Generic.Dictionary<int, Activity> _dataMap;
    private readonly System.Collections.Generic.List<Activity> _dataList;
    
    public TbActivity(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Activity>();
        _dataList = new System.Collections.Generic.List<Activity>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Activity _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Activity.DeserializeActivity(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Activity> DataMap => _dataMap;
    public System.Collections.Generic.List<Activity> DataList => _dataList;

    public Activity GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Activity Get(int key) => _dataMap[key];
    public Activity this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

